name: neutrino-server

services:
  neutrino-server:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    # command: tail -f /dev/null
    volumes:
      - ps2-roms-folder:/f:rw
    tty: true
    stdin_open: true
    # necessary for websocket connection
    network_mode: host
    
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"

volumes:
  ps2-roms-folder:
    driver_opts:
      type: none
      device: $PWD/roms
      o: bind
