name: neutrino-server

services:
  neutrino-server:
    image: ghcr.io/cptawe/ps2-neutrino-server:main
    volumes:
      - ps2-roms-folder:/f:rw
    tty: true
    stdin_open: true
    # necessary for websocket connection
    network_mode: host

    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
  
  copyparty:
    image: copyparty/ac:latest
    container_name: copyparty
    user: "1000:1000"
    ports:
      - 3923:3923
    volumes:
      - ./:/cfg:z
      - ps2-roms-folder:/w:z

    environment:
      LD_PRELOAD: /usr/lib/libmimalloc-secure.so.NOPE
      # enable mimalloc by replacing "NOPE" with "2" for a nice speed-boost (will use twice as much ram)

      PYTHONUNBUFFERED: 1
      # ensures log-messages are not delayed (but can reduce speed a tiny bit)

    stop_grace_period: 15s  # thumbnailer is allowed to continue finishing up for 10s after the shutdown signal
    healthcheck:
      # hide it from logs with "/._" so it matches the default --lf-url filter 
      test: ["CMD-SHELL", "wget --spider -q 127.0.0.1:3923/?reset=/._"]
      interval: 1m
      timeout: 2s
      retries: 5
      start_period: 15s

    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"

volumes:
  ps2-roms-folder:
    driver_opts:
      type: none
      device: $PWD/roms
      o: bind
